/* Site config + seed journal. Edit this file to change defaults. */
const SITE_CONFIG = {
  name: "Douglas Mitchell",
  email: "hello@douglasmitchell.info",
  github: "https://github.com/Senpai-Sama7",
  linkedin: "https://www.linkedin.com/in/douglas-mitchell-the-architect",
  adminUser: "admin",
  adminPass: "architect-2026",
  video: {
    src: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    poster: "",
    title: "In Conversation: The Operator's Craft"
  },
  consoleGreeting: "Signal acquired. I'm the public knowledge console for Douglas Mitchell \u2014 the Architect. Ask me about the book, the projects, the writing, his credentials, or how to start a conversation with him."
};

const SEED_POSTS = [
{
  id:"seed-rizz", slug:"rizz-prompting", featured:true, date:"2026-02-14", read:18,
  title:"Rizz Prompting: Attractor-Based Style Steering in LLMs",
  tags:["AI","Research"], accent:"gold", status:"published",
  excerpt:"Great prompting is less about commanding a model and more about arranging the conditions it naturally wants to continue. An editorial adaptation of the working paper.",
  body:"The strongest prompts do not force a model into a style. They stack contextual, lexical, structural, and persona cues until the desired response becomes statistically natural.\n\nMost people treat prompting like a vending machine: insert instruction, receive output. That works fine for retrieval and boilerplate. It fails the moment you need voice \u2014 the difference between text that reads like it was written and text that reads like it was *assembled*.\n\n## The core idea\n\nLanguage models are attractor systems. Every context you place them in defines a basin \u2014 a region of continuation space the model naturally falls into. Commanding \"write like a poet\" fights the current. Building a context where poetry is the path of least resistance rides it.\n\nFour cue classes do the heavy lifting:\n\n- **Contextual cues** \u2014 the situation, audience, and stakes surrounding the text\n- **Lexical cues** \u2014 vocabulary and phrasing that anchors the register\n- **Structural cues** \u2014 rhythm, cadence, and the shape of the response\n- **Persona cues** \u2014 who is speaking, and what they would never say\n\n## Why commanding fails\n\nAn instruction like \"be witty\" is a single weak signal competing against thousands of stronger priors baked into training data. Stack a witty frame, witty vocabulary, and a witty structural template, and the model doesn't have to *try* to be witty \u2014 wit becomes the natural continuation.\n\n> Style isn't commanded into existence. It's engineered into probability.\n\n## The practical playbook\n\nIterate like an operator, not a critic. Feed the model a draft context, watch what it produces unprompted, then reinforce whatever drifts toward your target register. You're not demanding behavior \u2014 you're observing the model's natural lean and tilting the floor.\n\nThe result is output that holds voice under pressure: long-form, multi-turn, edge cases. And once you internalize attractor thinking, every prompt you write starts looking less like a command and more like an environment design problem.\n\nThat's the whole thesis. Arrange conditions. Stack cues. Let probability do the heavy lifting. The model was always going to write something \u2014 your job is making the *something* inevitable."
},
{
  id:"seed-operators-lens", slug:"operators-lens", featured:false, date:"2026-06-02", read:12,
  title:"The Operator's Lens: What Operations Taught Me About AI Agents",
  tags:["AI","Systems"], accent:"teal", status:"published",
  excerpt:"AI agents are new hires with infinite stamina and zero context. Operations analysis is the onboarding manual they never gave you.",
  body:"Every operations analyst eventually learns the same lesson: work fails at the handoffs. Not at the hard problems \u2014 at the seams between people, tools, and decisions. Deploy enough AI agents and you learn it twice.\n\n## Agents are juniors with infinite stamina\n\nAn AI agent is a brilliant new hire with unlimited energy, perfect recall of its documentation, and absolutely no judgment about when to escalate. That's not an insult \u2014 it's a design spec. You wouldn't hand a new hire a production system with no runbook, no audit trail, and no escalation path. Yet that's exactly how most teams deploy agents.\n\nOperations analysis gives you the missing toolkit:\n\n- **Map the handoffs first.** Where does information change hands? Every handoff is an agent failure point.\n- **Define decision states explicitly.** In our automation work we mapped 40+ candidates and 8 distinct decision states before writing a line of integration code.\n- **Build audit trails before automation.** If you can't reconstruct why a decision happened, you can't safely automate it.\n\n## Throughput is a people metric\n\nThe instinct with agents is to measure volume \u2014 tickets closed, tasks completed. Operations people know better. Throughput that erodes trust isn't throughput; it's deferred failure. A system that resolves 500 requests but generates 40 escalations-to-nowhere has simply moved the queue somewhere you can't see it.\n\n## The human stays in the loop\n\nThe premium move is automation that preserves judgment: humans at the decision points that matter, machines everywhere else, and traceability across the whole thing. 100% coverage isn't a luxury \u2014 it's the difference between a system you trust and a system you babysit.\n\nAgents aren't replacing your operating model. They're stress-testing it. If the org chart was ambiguous before the agents, the agents will happily amplify that ambiguity at scale. Fix the seams first. The agents will thank you \u2014 in their own weird, probabilistic way."
},
{
  id:"seed-confidence-system", slug:"confidence-is-a-system", featured:false, date:"2026-03-19", read:9,
  title:"Confidence Is a System, Not a Feeling",
  tags:["Book","Writing"], accent:"rose", status:"published",
  excerpt:"You can't affirm your way to self-belief. The Confident Mind's core argument: confidence is built evidence, gathered through repetition \u2014 and it compounds.",
  body:"The self-help industry sells confidence as a feeling you can summon \u2014 recite the mantra, strike the pose, fake it till you make it. The Confident Mind starts from a harder, more useful premise: confidence is a system. Feelings are downstream of evidence.\n\n## The evidence engine\n\nConfidence that holds up under pressure comes from one place: a personal archive of done things. Not affirmations. Not visualization. Repetition \u2014 deliberate, slightly uncomfortable, consistently logged. Every rep is a data point. Enough data points and the belief stops being aspirational.\n\n- **Diagnose before you prescribe.** Understanding what actually broke your confidence beats reciting that it's whole.\n- **Move insight into action within 48 hours.** Reflection without a deadline is just sophisticated rumination.\n- **Log the evidence.** The mind discounts wins by default. A written record doesn't.\n\n## Anti-theater\n\nThe book is deliberately non-performative. No hype, no manufactured urgency, no six-figure-energy nonsense. Just a structured path: understanding the mechanics, closing the confidence gap, building internal evidence, applying it under real conditions, and sustaining it when life tests the structure.\n\n> Motivation is weather. Systems are climate.\n\n## Why this shows up in systems work\n\nThe same architecture shows up in everything I build: evidence over performance, repeatable practice over vague ambition, structures that help people act with clarity. Whether it's an operations pipeline or a psychological framework, the thesis holds \u2014 you don't rise to the level of your intentions, you fall to the level of your systems.\n\nThe book is the manual. The reps are on you."
},
{
  id:"seed-human-first", slug:"human-first-automation", featured:false, date:"2025-11-08", read:11,
  title:"Human-First Automation: Ship Leverage, Not Brittleness",
  tags:["Ops","AI"], accent:"violet", status:"published",
  excerpt:"Most automation projects fail the same way: they optimize the happy path and go brittle everywhere else. Three questions that separate leverage from liability.",
  body:"Every operations team eventually gets the pitch: automate it all, cut the headcount, let the robots run. And every operations team that survives the resulting incident learns the same distinction \u2014 there's automation that creates leverage, and automation that creates liability. The line between them is whether judgment survived the deployment.\n\n## The three-question filter\n\nBefore any automation ships, it answers three questions honestly:\n\n- **Does it reduce ambiguity?** If the automation makes the system harder to reason about, it's negative leverage with a nice dashboard.\n- **Does it fail gracefully?** Every automation fails eventually. The question is whether failure looks like a logged, routed exception \u2014 or a silent corruption you discover in a quarter.\n- **Does it keep a human at the decision points that matter?** Not everywhere. Just where judgment is the product.\n\n## Brittleness compounds\n\nThe seductive thing about automation is that the first 70% is cheap. The expensive 30% \u2014 edge cases, exceptions, the weird Tuesdays \u2014 is where projects die. Teams that skip the audit trail to hit a deadline don't skip the cost; they defer it, with interest, to the moment the system meets reality.\n\n> Automation is only premium when it preserves judgment, trust, and quality instead of adding brittle complexity.\n\n## The calm-systems standard\n\nThe goal isn't fewer humans. It's humans doing human work \u2014 judgment, relationships, exception handling \u2014 inside systems calm enough to be trusted. When an automation layer works, you barely notice it. Work just moves. Decisions just have receipts. People stop firefighting and start operating.\n\nThat's the standard. Ship leverage. Keep the receipts. Let the humans be human."
},
{
  id:"seed-85-repos", slug:"85-repos-later", featured:false, date:"2025-09-21", read:7,
  title:"85 Repos Later: What Building in Public Actually Teaches You",
  tags:["Systems","Meta"], accent:"gold", status:"published",
  excerpt:"85+ public repositories sounds like a flex. It's actually a ledger of every lesson I refused to learn twice \u2014 and a few I did.",
  body:"The GitHub counter says 85+ public repositories. What it doesn't say is how many of those are abandoned experiments, resurrected drafts, and one repo that exists purely so I never forget how DNS works. Building in public is less a content strategy than a forcing function.\n\n## Shipping small, shipping often\n\nA repo a week beats a masterpiece a year. Small, public, finishable projects teach you the full lifecycle \u2014 scope, build, document, deploy, move on \u2014 at a cadence where the lessons actually stick. Big secret projects rot quietly. Small public ones teach loudly.\n\n## The README is a contract\n\nSomewhere around repo thirty, I stopped writing READMEs as afterthoughts and started writing them as promises: what this is, what it isn't, how to run it, what broke. Turns out the primary audience for documentation is future you \u2014 and future you is a demanding client with no context.\n\n## Proof over posturing\n\nPublic work is unforgiving in the best way. The commit history doesn't care about your narrative. Stars are earned or they aren't. That honesty is the point \u2014 **proof over posturing** isn't a slogan, it's the natural output of a public ledger.\n\n- Version everything, even the experiments\n- Boring infrastructure wins more awards than clever hacks\n- The contribution graph is a trailing indicator, not a strategy\n\n## The honest math\n\n200+ stars, 500+ contributions, 12 languages \u2014 those numbers aren't impressive because they're big. They're useful because they're *traceable*. Every number maps to a commit you can read. That's the whole philosophy: work you can verify, shipped in the open, holding up in the real world.\n\nRepo eighty-six is already cooking. The ledger stays open."
}
];
